services:
  frontend:
    build:
      context: ./frontend/my-app   # Path to the folder with your React app
    ports:
      - "3000:3000"  # Map local port 3000 to the container's port 3000
    volumes:
      - ./frontend/my-app:/app
    environment:
      - NODE_ENV=development
  db:
    image: mysql:8.0  # Use MySQL 8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Adivinha12345!
      MYSQL_DATABASE: trellodb
      MYSQL_USER: root
      MYSQL_PASSWORD: Adivinha12345!
    ports:
      - "3306:3306"
    volumes:
      - ./data_base:/var/lib/mysql  # Persistent database storage